application/flicket/models/__init__.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

from application import db

Base = db.Model

application/flicket/forms/__init__.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

application/flicket/scripts/forms.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#


# used for debugging purposes only
def print_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            print("Error in the {} field - {}".format(
                getattr(form, field).label.text,
                error
            ))

application/flicket/__init__.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

application/flicket/scripts/__init__.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

application/flicket/views/__init__.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

from flask import Blueprint

import os

static_folder = os.path.join(os.getcwd(), 'application/flicket/static')

flicket_bp = Blueprint('flicket_bp', __name__,
                       template_folder="../templates",
                       static_folder=static_folder,
                       static_url_path='/flicket/static',
                       )

application/flicket/views/assign.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

import datetime

from flask import redirect, url_for, flash, render_template
from flask_babel import gettext
from flask_login import login_required

from application import app, db
from application.flicket.forms.flicket_forms import AssignUserForm
from application.flicket.models.flicket_models import FlicketTicket, FlicketStatus, FlicketSubscription
from application.flicket.models.flicket_user import FlicketUser
from application.flicket.scripts.flicket_functions import add_action
from application.flicket.scripts.email import FlicketMail
from . import flicket_bp


# tickets main
@flicket_bp.route(app.config['FLICKET'] + 'ticket_assign/<int:ticket_id>/', methods=['GET', 'POST'])
@login_required
def ticket_assign(ticket_id=False):
    form = AssignUserForm()
    ticket = FlicketTicket.query.filter_by(id=ticket_id).one()

    if ticket.current_status.status == 'Closed':
        flash(gettext("Can't assign a closed ticket."), category='warning')
        return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket_id))

    if form.validate_on_submit():

        user = FlicketUser.query.filter_by(username=form.username.data).first()

        if ticket.assigned == user:
            flash(gettext('User is already assigned to ticket.'), category='warning')
            return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket.id))

        # set status to in work
        status = FlicketStatus.query.filter_by(status='In Work').first()
        # assign ticket
        ticket.assigned = user
        ticket.current_status = status
        ticket.last_updated = datetime.datetime.now()

        if not user.total_assigned:
            user.total_assigned = 1
        else:
            user.total_assigned += 1

        # add action record
        add_action(ticket, 'assign', recipient=user)

        # subscribe to the ticket
        if not ticket.is_subscribed(user):
            subscribe = FlicketSubscription(
                ticket=ticket,
                user=user
            )
            db.session.add(subscribe)

        db.session.commit()

        # send email to state ticket has been assigned.
        f_mail = FlicketMail()
        f_mail.assign_ticket(ticket)

        flash(gettext('You reassigned ticket: {} to {}'.format(ticket.id, user.name)), category='success')
        return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket.id))

    title = gettext('Assign Ticket')

    return render_template("flicket_assign.html", title=title, form=form, ticket=ticket)

application/flicket/views/categories.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

from flask import flash, redirect, url_for, render_template
from flask_login import login_required
from flask_babel import gettext

from . import flicket_bp
from application import app, db
from application.flicket.forms.flicket_forms import CategoryForm
from application.flicket.models.flicket_models import FlicketCategory, FlicketDepartment


# create ticket
@flicket_bp.route(app.config['FLICKET'] + 'categories/<int:department_id>/', methods=['GET', 'POST'])
@login_required
def categories(department_id=False):
    form = CategoryForm()
    categories = FlicketCategory.query.order_by(FlicketCategory.category.asc()).filter_by(department_id=department_id)
    department = FlicketDepartment.query.filter_by(id=department_id).first()

    form.department_id.data = department_id

    if form.validate_on_submit():
        add_category = FlicketCategory(category=form.category.data, department=department)
        db.session.add(add_category)
        db.session.commit()
        flash(gettext('New category {} added.'.format(form.category.data)), category="success")
        return redirect(url_for('flicket_bp.categories', department_id=department_id))

    title = gettext('کتگوری ها')

    return render_template('flicket_categories.html',
                           title=title,
                           form=form,
                           categories=categories,
                           department=department)


@flicket_bp.route(app.config['FLICKET'] + 'category_edit/<int:category_id>/', methods=['GET', 'POST'])
@login_required
def category_edit(category_id=False):
    if category_id:

        form = CategoryForm()
        category = FlicketCategory.query.filter_by(id=category_id).first()
        form.department_id.data = category.department_id

        if form.validate_on_submit():
            category.category = form.category.data
            db.session.commit()
            flash('Category {} edited.'.format(form.category.data), category='success')
            return redirect(url_for('flicket_bp.departments'))

        form.category.data = category.category

        title = gettext('ویرایش کتگوری')

        return render_template('flicket_category_edit.html',
                               title=title,
                               form=form,
                               category=category,
                               department=category.department.department
                               )

    return redirect(url_for('flicket_bp.departments'))

application/flicket/views/claim.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

import datetime

from flask import redirect, url_for, flash, g
from flask_babel import gettext
from flask_login import login_required

from . import flicket_bp
from application import app, db
from application.flicket.models.flicket_models import FlicketTicket, FlicketStatus
from application.flicket.scripts.flicket_functions import add_action
from application.flicket.scripts.email import FlicketMail


# view for self claim a ticket
@flicket_bp.route(app.config['FLICKET'] + 'ticket_claim/<int:ticket_id>/', methods=['GET', 'POST'])
@login_required
def ticket_claim(ticket_id=False):
    if ticket_id:
        # claim ticket
        ticket = FlicketTicket.query.filter_by(id=ticket_id).first()

        if ticket.assigned == g.user:
            flash(gettext('You have already been assigned this ticket.'), category='success')
            return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket.id))

        # set status to in work
        status = FlicketStatus.query.filter_by(status='In Work').first()
        ticket.assigned = g.user
        g.user.total_assigned += 1
        ticket.current_status = status
        ticket.last_updated = datetime.datetime.now()
        db.session.commit()

        # add action record
        add_action(ticket, 'claim')

        # send email notifications
        f_mail = FlicketMail()
        f_mail.assign_ticket(ticket=ticket)

        flash(gettext('You claimed ticket: %(value)s', value=ticket.id))
        return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket.id))

    return redirect(url_for('flicket_bp.tickets'))

application/flicket/views/create.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

from flask import (flash,
                   redirect,
                   url_for,
                   request,
                   session,
                   render_template,
                   g)
from flask_babel import gettext
from flask_login import login_required

from . import flicket_bp
from application import app
from application.flicket.forms.flicket_forms import CreateTicketForm
from application.flicket.models.flicket_models_ext import FlicketTicketExt


# create ticket
@flicket_bp.route(app.config['FLICKET'] + 'ticket_create/', methods=['GET', 'POST'])
@login_required
def ticket_create():
    # default category based on last submit (get from session)
    # using session, as information about last created ticket can be sensitive
    # in future it can be stored in extended user model instead
    last_category = session.get('ticket_create_last_category')
    form = CreateTicketForm(category=last_category)

    if form.validate_on_submit():
        new_ticket = FlicketTicketExt.create_ticket(title=form.title.data,
                                                    user=g.user,
                                                    content=form.content.data,
                                                    category=form.category.data,
                                                    priority=form.priority.data,
                                                    hours=form.hours.data,
                                                    files=request.files.getlist("file"))

        flash(gettext('New Ticket created.'), category='success')

        session['ticket_create_last_category'] = form.category.data

        return redirect(url_for('flicket_bp.ticket_view', ticket_id=new_ticket.id))

    title = gettext('ساخت تیکت')
    return render_template('flicket_create.html', title=title, form=form)

application/flicket/views/delete.py
#! usr/bin/python3
# -*- coding: utf-8 -*-
#

import os

from flask import flash, g, redirect, url_for, render_template
from flask_babel import gettext
from flask_login import login_required

from application import app, db
from application.flicket.forms.forms_main import ConfirmPassword
from application.flicket.models.flicket_models import (FlicketTicket,
                                                       FlicketUploads,
                                                       FlicketPost,
                                                       FlicketCategory,
                                                       FlicketDepartment,
                                                       FlicketHistory)
from . import flicket_bp


# delete ticket
@flicket_bp.route(app.config['FLICKET'] + 'delete_ticket/<ticket_id>/', methods=['GET', 'POST'])
@login_required
def delete_ticket(ticket_id):
    # check is user is authorised to delete tickets. Currently, only admins can delete tickets.
    if not g.user.is_admin:
        flash(gettext('You are not authorised to delete tickets.'), category='warning')
        return redirect(url_for('flicket_bp.ticket_view', ticket_id=ticket_id))

    form = ConfirmPassword()

    ticket = FlicketTicket.query.filter_by(id=ticket_id).first()

    if form.validate_on_submit():

        # delete images from database and folder
        images = FlicketUploads.query.filter_by(topic_id=ticket_id)
        for i in images:
            # delete files
            os.remove(os.path.join(os.getcwd(), app.config['ticket_upload_folder'] + '/' + i.file_name))
            # remove from database
            db.session.delete(i)

        # remove posts for ticket.
        for post in ticket.posts:
            # remove history
            history = FlicketHistory.query.filter_by(post=post).all()
            for h in history:
                db.session.delete(h)
            post.user.total_posts -= 1
            db.session.delete(post)

        user = ticket.user
        user.total_posts -= 1
        db.session.delete(ticket)

        # commit changes
        db.session.commit()
        flash(gettext('Ticket deleted.'), category='success')
        return redirect(url_for('flicket_bp.tickets'))

    return render_template('flicket_deletetopic.html',
                           form=form,
                           ticket=ticket,
                           title='حذف تیکت')


# delete post
@flicket_bp.route(app.config['FLICKET'] + 'delete_post/<post_id>/', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    # check user is authorised to delete posts. Only admin can do this.
    if not g.user.is_admin:
        flash(gettext('You are not authorised to delete posts'), category='warning')

    form = ConfirmPassword()

    post = FlicketPost.query.filter_by(id=post_id).first()

    if form.validate_on_submit():

        # delete images from database and folder
        images = FlicketUploads.query.filter_by(posts_id=post_id)
        for i in images:
            # delete files
            os.remove(os.path.join(os.getcwd(), app.config['ticket_upload_folder'] + '/' + i.file_name))
            # remove from database
            db.session.delete(i)

        db.session.delete(post)
        # commit changes
        db.session.commit()
        flash(gettext('Ticket deleted.'), category='success')
        return redirect(url_for('flicket_bp.tickets'))

    title = gettext('Delete Post')

    return render_template('flicket_deletepost.html',
                           form=form,
                           post=post,
                           title=title)


# delete category
@flicket_bp.route(app.config['FLICKET'] + 'delete/category/<int:category_id>/', methods=['GET', 'POST'])
@login_required
def delete_category(category_id=False):
    if category_id:

        # check user is authorised to delete categories. Only admin or super_user can do this.
        if not any([g.user.is_admin, g.user.is_super_user]):
            flash(gettext('You are not authorised to delete categories.'), category='warning')
            return redirect('flicket_bp.departments')

        form = ConfirmPassword()

        categories = FlicketTicket.query.filter_by(category_id=category_id)
        category = FlicketCategory.query.filter_by(id=category_id).first()

        # stop the deletion of categories assigned to tickets.
        if categories.count() > 0:
            flash(
                gettext(
                    ('Category is linked to posts. Category can not be deleted unless all posts / topics are removed'
                     ' / relinked.')),
                category="danger")
            return redirect(url_for('flicket_bp.departments'))

        if form.validate_on_submit():
            # delete category from database
            category = FlicketCategory.query.filter_by(id=category_id).first()

            db.session.delete(category)
            # commit changes
            db.session.commit()
            flash('Category deleted', category='success')
            return redirect(url_for('flicket_bp.departments'))

        notification = "You are trying to delete category: {} that belongs " \
                       "to department: {}.".format(category.category.upper(), category.department.department.upper())

        title = gettext('حذف کتگوری')

        return render_template('flicket_delete.html',
                               form=form,
                               notification=notification,
                               title=title)


# delete department
@flicket_bp.route(app.config['FLICKET'] + 'delete/department/<int:department_id>/', methods=['GET', 'POST'])
@login_required
def delete_department(department_id=False):
    if department_id:

        # check user is authorised to delete departments. Only admin or super_user can do this.
        if not any([g.user.is_admin, g.user.is_super_user]):
            flash(gettext('You are not authorised to delete departments.'), category='warning')
            return redirect('flicket_bp.departments')

        form = ConfirmPassword()

        #
        departments = FlicketCategory.query.filter_by(department_id=department_id)
        department = FlicketDepartment.query.filter_by(id=department_id).first()

        # we can't delete any departments associated with categories.
        if departments.count() > 0:
            flash(gettext(
                ('Department has categories linked to it. Department can not be deleted unless all categories are '
                 'first removed.')),
                category="danger")
            return redirect(url_for('flicket_bp.departments'))

        if form.validate_on_submit():
            # delete category from database
            department = FlicketDepartment.query.filter_by(id=department_id).first()

            db.session.delete(department)
            # commit changes
            db.session.commit()
            flash('Department "{}" deleted.'.format(department.department), category='success')
            return redirect(url_for('flicket_bp.departments'))

        notification = gettext(
            "You are trying to delete department: %(value)s.",
            value=department.department.upper())

        title = gettext('حذف دپارتمان')

        return render_template('flicket_delete.html',
                               form=form,
                               notification=notification,
                               title=title)

application/flicket/templates/email_include_details.html
<table>
    <tr>
        <th style="text-align: left">{{ _('Status') }}</th>
        <td>{{ ticket.current_status.status }}</td>
    </tr>
    <tr>
        <th style="text-align: left">{{ _('Priority') }}</th>
        <td>{{ ticket.ticket_priority.priority }}</td>
    </tr>
    <tr>
        <th style="text-align: left">{{ _('Assigned') }}</th>
        <td>{% if ticket.assigned.username %}{{ ticket.assigned.name }}{% else %}ticket not claimed{% endif %}</td>
    </tr>
    <tr>
        <th style="text-align: left; vertical-align: text-top">{{ _('Content') }}</th>
        <td>{{ ticket.content }}</td>
    </tr>
</table>

application/flicket/templates/email_ticket_assign.html
{% extends "email_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <h1>
        {{ title }}
    </h1>
    <p>
        {{ ticket.assigned.name }} {{ _('has been assigned to ticket:') }} <a href="{{ ticket_url }}">{{ number }}</a>
    </p>
    {% include('email_include_details.html') %}

{% endblock %}

application/flicket/templates/email_ticket_department_category.html
{% extends "email_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <h1>
        {{ title }}
    </h1>
    <p>
    {{ _('Department') }} / {{_('Category') }} "{{ ticket.department_category }}" {{ _('has been assigned to ticket:') }} <a href="{{ ticket_url }}">{{ number }}</a>
    </p>
    {% include('email_include_details.html') %}

{% endblock %}

application/flicket/templates/email_ticket_release.html
{% extends "email_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <h1>
        {{ title }}
    </h1>
    <p>
        {{ _('Ticket has been released. Ticket is now no longer assigned to anyone. Ticket:') }} <a href="{{ ticket_url }}">{{ number }}</a>
    </p>
    {% include('email_include_details.html') %}

{% endblock %}

application/flicket/templates/email_ticket_replies.html
{% extends "email_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <h1>
        {{ title }}
    </h1>
    {% include('email_include_details.html') %}
    <p>
        {{ _('There are new replies to ticket:') }} <a href="{{ ticket_url }}">{{ number }}</a>.
    </p>
    <p>
        {{ reply.user.name }} replied:<br>
        "{{ reply.content }}"
    </p>
{% endblock %}

application/flicket/templates/flicket_assign.html
{% extends "flicket_base.html" %}
<!-- extend from base layout -->
{% block content %}

    {% include('flicket_apijson_users.html') %}

    <div class="container">

        <div class="row m-2 p-2 border rounded bg-white">
            <div class="col">
                <h1>{{ title }}</h1>
                <h2 class="flicket-title">#{{ ticket.id_zfill }} - {{ ticket.title }}</h2>
            </div>
        </div>

        <div class="row m-2 p-2 border rounded bg-white">
            <div class="col">

                <div class="row mb-2">
                    <div class="col">
                        {{ _('Type name and pick from drop down list to assign ticket. ') }}
                        <a href="{{ url_for('flicket_bp.flicket_users') }}" target="_blank">
                            Available users
                        </a>
                    </div>
                </div>
                <form action=""
                      class=""
                      enctype="multipart/form-data"
                      method="post"
                      name="create_ticket">
                    {{ form.hidden_tag() }}
                    <div class="row">
                        <label class="col-2 col-form-label"
                               for="autocomplete-username">{{ form.username.label }}</label>
                        <div class="col-sm-3">
                            {{ form.username(class="form-control form-control-sm", id="autocomplete-username") }}
                            {% if form.username.errors %}
                                <div class="alert alert-warning small">
                                    {% for error in form.username.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                    </div>
                    <div class="row">
                        <div class="col text-center">
                            {{ form.submit }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

application/flicket/templates/flicket_base.html
<!DOCTYPE html>
<html lang="en-GB">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ g.application_title }}{% if title %} - {{ title }} {% endif %}</title>


    <link rel="stylesheet" href="{{ url_for('flicket_bp.static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('flicket_bp.static', filename='css/flicket.css') }}">
    <link rel="stylesheet" href="{{ url_for('flicket_bp.static', filename='css/jquery-ui.min.css') }}">

    <script src="{{ url_for('flicket_bp.static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('flicket_bp.static', filename='js/jquery-ui.js') }}"></script>
    <script src="{{ url_for('flicket_bp.static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('flicket_bp.static', filename='js/hide_element.js') }}"></script>
    <script src="{{ url_for('flicket_bp.static', filename='js/all.js') }}"></script>

    <link rel="shortcut icon" href="{{ url_for('flicket_bp.static', filename='icons/favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('flicket_bp.static', filename='icons/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('flicket_bp.static', filename='icons/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('flicket_bp.static', filename='icons/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('flicket_bp.static', filename='icons/site.webmanifest') }}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>
<body>

{% include 'flicket_navbar.html' %}
<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col pt-5 text-right" style="font-size: 2rem">
                {{ g.application_title }}
                <span style="font-size: 0.8rem; color: black">
                    {{ _('سامانه ی ساده ی تیکت') }}
                </span>
            </div>
        </div>
    </div>
</header>
{% include 'flicket_flashmessages.html' %}
{% block content %}{% endblock %}
{% include 'flicket_footer.html' %}

</body>
</html>

application/flicket/templates/flicket_create.html
{% extends "flicket_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <!-- {{ self._TemplateReference__context.name }} -->
    <div class="container">
        <h1 class="m-2 border rounded bg-white p-2 text-right">{{ title }}</h1>
        {% include 'flicket_post_box.html' %}
    </div>
{% endblock %}

application/flicket/templates/flicket_departments.html
{% extends "flicket_base.html" %}
<!-- extend from base layout -->
{% block content %}
    <div class="container">
        <div class="row bg-white m-2 border round">
            <div class="col">
                <h1 class="text-right">{{ title }}</h1>
                <p class="text-right">{{ _('.برای ساخت / حذف دپارتمان / کتگوری لطفا تیکت بزنید') }}</p>
            </div>
        </div>


        <div class="row m-2 bg-white border rounded p-2">
            <form action=""
                  class="col form form-inline"
                  enctype="multipart/form-data"
                  method="post"
                  name="create_ticket">
                {{ form.hidden_tag() }}
                <label class="sr-only">{{ form.department.label }}</label>
                <div class="col-md-6 col-12 mb-1">
                    {{ form.department(class="form-control form-control-sm", placeholder="دپارتمان") }}
                </div>
                <div class="col-md-6 col text-center">
                    {{ form.submit }}
                </div>
                {% if form.department.errors %}
                    <div class="alert alert-warning small">
                        {% for error in form.department.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>


        <ul class="pagination pagination-sm m-2">
            <li class="page-item {% if not departments.has_prev -%} disabled {%- endif -%} ">
                <a class="page-link"
                   href="{{ url_for('flicket_bp.departments', page=departments.prev_num, **request.args) }}">
                    <<
                </a>
            </li>

            {%- for page in departments.iter_pages() -%}
                {%- if page -%}
                    {%- if page != departments.page -%}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for('flicket_bp.departments', page=page, **request.args) }}">
                                {{ page }}
                            </a>
                        </li>
                    {%- else -%}
                        <li class="page-item active">
                            <a class="page-link active"
                               href="{{ url_for('flicket_bp.departments', page=page, **request.args) }}">
                                {{ page }}
                            </a>
                        </li>
                    {%- endif -%}
                {%- else -%}
                    <li class="page-item">
                        <a class="page-link" href="">...</a>
                    </li>
                {%- endif -%}
            {%- endfor -%}

            <li class="page-item {% if not departments.has_next -%} disabled {%- endif -%} ">
                <a class="page-link"
                   href="{{ url_for('flicket_bp.departments', page=departments.next_num, **request.args) }}">
                    >>
                </a>
            </li>

        </ul>

        <div class="row m-2 border rounded bg-white">
            <div class="col">
                <div class="row border-bottom p-2">
                    <div class="col">
                        {{ _('دپارتمان') }}
                    </div>
                    <div class="col">
                        {{ _('کتگوری ها') }}
                    </div>
                </div>
                {%- for d in departments.items -%}
                    <div class="row p-2">
                        <div class="col">
                            {{ d.department }}
                            {%- if g.user.is_admin or g.user.is_super_user -%}

                                <a href="{{ url_for('flicket_bp.department_edit', department_id=d.id) }}"
                                   title="edit">
                                    <i class="fas fa-edit"></i>
                                </a>

                                <a href="{{ url_for('flicket_bp.delete_department', department_id=d.id) }}"
                                   title="delete">
                                    <i class="fas fa-trash" style="color: red"></i>
                                </a>

                            {%- endif -%}
                        </div>
                        <div class="col">
                            {%- for c in d.categories -%}
                                {{ c.category }}
                                {%- if g.user.is_admin or g.user.is_super_user -%}
                                    <a href="{{ url_for('flicket_bp.category_edit', category_id=c.id) }}"
                                       title="edit">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="{{ url_for('flicket_bp.delete_category', category_id=c.id) }}"
                                       title="delete">
                                        <i class="fas fa-trash" style="color: red"></i>
                                    </a>
                                {%- endif -%}
                            {%- endfor -%}
                            {%- if g.user.is_admin or g.user.is_super_user -%}
                                <a href="{{ url_for('flicket_bp.categories', department_id=d.id) }}">
                                    <i class="fas fa-plus"></i>
                                </a>
                            {%- endif -%}
                        </div>
                    </div>
                {%- endfor -%}
            </div>

        </div>
    </div>

{% endblock %}